<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23935" started-at="2021-05-19T13:30:23 ICT" finished-at="2021-05-19T13:30:47 ICT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23935" started-at="2021-05-19T13:30:23 ICT" finished-at="2021-05-19T13:30:47 ICT">
      <class name="excute.TS_ThemSach">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:excute.TS_ThemSach@76a3e297]" name="beforeMethod" is-config="true" duration-ms="7942" started-at="2021-05-19T13:30:23 ICT" finished-at="2021-05-19T13:30:31 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC_01_ThemThanhCong()[pri:0, instance:excute.TS_ThemSach@76a3e297]" name="TC_01_ThemThanhCong" duration-ms="15757" started-at="2021-05-19T13:30:31 ICT" finished-at="2021-05-19T13:30:46 ICT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Du lieu so sanh co 1 truong bi null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Du lieu so sanh co 1 truong bi null
at org.testng.Assert.fail(Assert.java:99)
at common.CommonBase.verifyCompare(CommonBase.java:589)
at excute.TS_ThemSach.TC_01_ThemThanhCong(TS_ThemSach.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_ThemThanhCong -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:excute.TS_ThemSach@76a3e297]" name="afterMethod" is-config="true" duration-ms="183" started-at="2021-05-19T13:30:47 ICT" finished-at="2021-05-19T13:30:47 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- excute.TS_ThemSach -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
